# Generated by Django 4.1.2 on 2022-11-16 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealership', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
                ('year', models.IntegerField(default=0)),
                ('color', models.CharField(max_length=20)),
                ('mileage', models.IntegerField(default=0)),
                ('cleanTitle', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='destination',
            name='trip_category',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Destination',
        ),
        migrations.DeleteModel(
            name='TripCategory',
        ),
    ]
